- name: Variable from inventory
  hosts: localhost
  connection: local
  vars:
    student:
      name: Imran
      course: DevOps
  tasks:
#    - name: Copy filr
#      ansible.builtin.copy:
#        src: sample.txt
#        dest: /tmp/h1.txt

    - name: copt tem
      ansible.builtin.template:
        src: sample.txt.j2
        dest: /tmp/output.txt